apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order
  namespace: msusers-ns
  labels:
    app: order
spec:
  endpoints:
    - port: metrics
      scrapeTimeout: 30s
      path: "/actuator/prometheus"     
#  jobLabel: stack
  selector:
    matchLabels:
      app: order